# Generated by Django 5.0.2 on 2024-03-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_details_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
