# Generated by Django 5.0.2 on 2024-03-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_details_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='type',
        ),
    ]
