# Generated by Django 5.0.2 on 2024-03-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_details_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='category_type',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
