# Generated by Django 5.0.2 on 2024-03-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='author_image',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='author_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='publish_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='short_description',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
