# Generated by Django 5.0.2 on 2024-03-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_details_create_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
