# Generated by Django 5.0.2 on 2024-03-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_details_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
