# Generated by Django 5.0.2 on 2024-02-21 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(default=None, max_length=100)),
                ('event_description', models.CharField(default=None, max_length=1000)),
                ('price', models.IntegerField()),
                ('event_date', models.DateField()),
                ('publish_date', models.DateField()),
                ('event_start_time', models.CharField(max_length=100)),
                ('event_end_time', models.CharField(max_length=100)),
                ('event_address', models.CharField(default=None, max_length=500)),
                ('event_address_latitude', models.CharField(default=None, max_length=100)),
                ('event_address_longitude', models.CharField(default=None, max_length=100)),
                ('event_image', models.CharField(default=None, max_length=100, null=True)),
                ('number_of_people', models.IntegerField()),
                ('organizer_name', models.CharField(default=None, max_length=500)),
                ('organizer_contact_number', models.CharField(default=None, max_length=100)),
                ('organizer_description', models.CharField(default=None, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_category_id', to='category.details')),
            ],
        ),
    ]
