# Generated by Django 5.0.2 on 2024-03-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_booking_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='number_of_seat',
            field=models.IntegerField(default=0),
        ),
    ]
