# Generated by Django 5.0.2 on 2024-03-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_details_created_at_details_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='event_type',
            new_name='is_vip_seat',
        ),
        migrations.RemoveField(
            model_name='details',
            name='number_of_people',
        ),
    ]
