# Generated by Django 5.0.2 on 2024-03-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_remove_details_organizer_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='organizer_description',
        ),
    ]
