# Generated by Django 5.0.2 on 2024-03-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_gallery_upload_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
