# Generated by Django 5.0.2 on 2024-03-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_gallery_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='organizer_image',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
