# Generated by Django 5.0.2 on 2024-02-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
