# Generated by Django 5.0.2 on 2024-02-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_details_address_details_dob_details_family_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='relation',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='step1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='details',
            name='step2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='details',
            name='step3',
            field=models.BooleanField(default=False),
        ),
    ]
