# Generated by Django 5.0.2 on 2024-02-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_details_relation_details_step1_details_step2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='email_otp',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='details',
            name='email_otp_expier',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='details',
            name='mobile_otp',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='details',
            name='mobile_otp_expier',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='mobile_verified',
            field=models.BooleanField(default=False),
        ),
    ]
