# Generated by Django 5.0.2 on 2024-02-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_details_email_otp_details_email_otp_expier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='mobile',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
