# Generated by Django 5.0.2 on 2024-02-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_details_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='relation',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
