# Generated by Django 5.0.2 on 2024-02-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_details_email_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='dob',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
