# Generated by Django 5.0.2 on 2024-02-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_details_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='sub_member',
            field=models.BooleanField(default=False),
        ),
    ]
