# Generated by Django 5.0.2 on 2024-02-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_details_sub_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='step4',
            field=models.BooleanField(default=False),
        ),
    ]
