# Generated by Django 5.0.2 on 2024-02-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_details_step4'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='profile_image',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
