# Generated by Django 5.0.2 on 2024-02-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_details_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
