# Generated by Django 5.0.2 on 2024-02-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_details_family_id_alter_details_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='profession_description',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
