# Generated by Django 5.0.2 on 2024-03-14 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='book_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.BooleanField(default=False),
        ),
    ]
