# Generated by Django 5.0.2 on 2024-03-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_event_created_at_event_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default='Upcoming', max_length=100, null=True),
        ),
    ]
