# Generated by Django 5.0.2 on 2024-03-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_number',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
