# Generated by Django 5.0.2 on 2024-03-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_event_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='transaction_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
