# Generated by Django 5.0.2 on 2024-03-19 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0012_2_8'),
        ('event', '0008_details_created_at_details_updated_at_and_more'),
        ('user', '0020_event_transaction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.details')),
                ('payment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djstripe.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
