# Generated by Django 5.0.2 on 2024-03-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_event_payment_delete_eventpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='account_status',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
