# Generated by Django 5.0.2 on 2024-03-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_details_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
