# Generated by Django 5.0.2 on 2024-03-26 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0012_2_8'),
        ('donation', '0007_details_is_active'),
        ('user', '0024_alter_event_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_status', models.CharField(max_length=100, null=True)),
                ('is_name_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.details')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_donation_payment', to='djstripe.webhookeventtrigger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
