# Generated by Django 5.0.2 on 2024-03-26 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0012_2_8'),
        ('user', '0025_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_donation_payment', to='djstripe.webhookeventtrigger'),
        ),
    ]
