# Generated by Django 5.0.2 on 2024-03-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_achievments'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievments',
            name='upwork',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
