# Generated by Django 5.0.2 on 2024-03-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_achievments_upwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievments',
            name='image',
        ),
        migrations.RemoveField(
            model_name='achievments',
            name='linkdin',
        ),
        migrations.RemoveField(
            model_name='achievments',
            name='upwork',
        ),
        migrations.AddField(
            model_name='achievments',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
