# Generated by Django 5.0.2 on 2024-03-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_remove_achievments_image_remove_achievments_linkdin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievments',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
