# Generated by Django 5.0.2 on 2024-03-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_achievments_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='background_image',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='linkdin',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='upwork',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
