# Generated by Django 5.0.2 on 2024-03-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_details_background_image_details_linkdin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(default=None, max_length=2000, null=True)),
            ],
        ),
    ]
