# Generated by Django 5.0.2 on 2024-03-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='subtitle',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='title',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
