# Generated by Django 5.0.2 on 2024-04-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_bannerimage_subtitle_bannerimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='certification_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
