# Generated by Django 5.0.2 on 2024-03-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(default=None, max_length=100, null=True)),
                ('donation_name', models.CharField(default=None, max_length=100)),
                ('donation_target', models.IntegerField()),
                ('donation_start_date', models.DateField()),
                ('donation_end_date', models.DateField()),
                ('location', models.CharField(default=None, max_length=100)),
                ('donation_address', models.CharField(default=None, max_length=1000, null=True)),
                ('description', models.CharField(default=None, max_length=1000, null=True)),
                ('organizer_name', models.CharField(default=None, max_length=1000, null=True)),
                ('organizer_contact', models.CharField(default=None, max_length=1000, null=True)),
            ],
        ),
    ]
