# Generated by Django 5.0.2 on 2024-03-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_details_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='donation_target',
            field=models.FloatField(),
        ),
    ]
