# Generated by Django 5.0.2 on 2024-03-22 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_alter_details_donation_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='donation_create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='details',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
