# Generated by Django 5.0.2 on 2024-03-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_details_created_at_details_donation_create_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='location',
        ),
        migrations.AddField(
            model_name='details',
            name='donation_city',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='donation_state',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
