# Generated by Django 5.0.2 on 2024-03-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_details_organizer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
